export const CREATE_CONTACT = "CREATE_CONTACT";
export const GET_CONTACT = "GET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DEL_CONTACT = "REMOVE_CONTACT";
export const CLEAR_LIST = "CLEAR_LIST";
